[tool.poetry]
name = "fiks-cpu"
version = "0.1.0"
description = ""
authors = ["Petr Šťastný <petr.stastny@second-foundation.eu>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

